{
    "swagger": "2.0",
    "info": {
      "description": "Welcome to the Free Mentors system documentation.",
      "version": "1.0.0",
      "title": "Free Mentor",
      "termsOfService": "https://murera.github.io/FreeMentor/UI/",
      "contact": {
        "email": "amanidiope@gmail.com"
      },
      "license": {
        "name": "Apache 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
      }
    },
    "host": "https://free-mentorship.herokuapp.com/",
    "basePath": "/api/v1",
    "tags": [
      {
        "name": "signup",
        "description": "Creates a new user"
      },
      {
        "name": "signin",
        "description": "Log in an existing user"
      },
      {
        "name": "Change user to Mentor",
        "description": "Admin can change a user to mentor"
      },
      {
        "name": "view all Mentors",
        "description": "view all Available mentors"
      },
      {
        "name": "Specific mentor",
        "description": "view specific mentor"
      },
      {
        "name": "Create Mentorship session",
        "description": "user can create mentorship session"
      },
      {
        "name": "Reject Mentorship session",
        "description": "mentor can reject mentorship session request"
      },
      {
        "name": "Accept Mentorship session",
        "description": "mentor can accept mentorship session request"
      }
    ],
    "schemes": [
      "http"
    ],
    "paths": {
      "/signup": {
        "post": {
          "tags": [
            "signup"
          ],
          "summary": "Create New Account",
          "description": "If you don't have account yet register",
          "operationId": "createUser",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "in": "body",
              "name": "body",
              "description": "Created user object",
              "required": true,
              "schema": {
                "$ref": "#/definitions/User"
              }
            }
          ],
          "responses": {
            "201": {
              "description": "User created successfully",
              "schema": {
                "type": "object",
                "example":{
                    "status": 201,
                    "message": "User created successfully",
                    "data": {
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNTY3Mjg2NTIxfQ.fJyiqLzJPs8D3NiUz_a0-NQBN1YUEfAP3sIyjhNkaqk",
                        "id": 1,
                        "first_name": "Amani",
                        "last_name": "Murera",
                        "email": "amanidiope@gmail.com",
                        "password": "dangerous",
                        "address": "kigali",
                       " bio": "engineer",
                        "occupation":"engineer",
                        "expertise": "software"
                    }
                }
              }
            },
            "409": {
              "description": "user already exist"
            },
            "400": {
                "description": "bad request"
              }
          }
        }
      },
      "/signin": {
        "post": {
          "tags": [
            "signin"
          ],
          "summary": "user sign in the system",
          "description": "",
          "operationId": "loginUser",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "in": "body",
              "name": "body",
              "description": "login user object",
              "required": true,
              "schema": {
                "$ref": "#/definitions/login"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "user successful login",
              "schema": {
                "type": "string",
                "example":{
                  "status": 200,
                  
                  "message": "User successfully signed in",
                  "data": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaXNfYWRtaW4iOmZhbHNlLCJpc19tZW50b3IiOnRydWUsImlhdCI6MTU2NzQyMjI1NH0.M3Fa5rHGyZUDLBg3XfKzhz5ERfDMLBzQmDM2sdTwKik",
                  "first_name": "Amani",
                  "last_name": "Murera",
                  "email": "ericirakoze@gmail.com"
                   }
                }
              }
            },
            "400": {
              "description": "bad request"
            },
            "401":{
              "description": "email or password is incorrect"
            }
            
          }
        }
      },
      "/user/<:id:>": {
          "patch": {
            "tags": [
              "Change user to Mentor"
            ],
            "summary": "change user to mentor",
            "description": "",
            "operationId": "getuserById",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "description": "ID of the user",
                "required": true,
                "type": "integer",
                "format": "int64"
              },
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token must be providen in request header"
               }
            ],
            "responses": {
              "200": {
                "description": "User account changed to mentor",
                "schema":{
                  "type": "object",
                  "example":{
                    "status": 200,
                    "data": {
                        "message": "User account changed to mentor",
                        "id": 2,
                        "first_name": "habimana",
                        "last_name": "emmy",
                        "email": "amani@gmail.com",
                        "address": "kigali",
                        "bio": "doctor",
                        "status": "mentor",
                        "occupation": "doctor",
                        "expertise": "doctor"
                    }
                  }
                }
              },
              "403": {
                "description": "you are not an admin"
              },
              "404": {
                "description": "user not found"
              }
            }
          }
        },
        "/mentors": {
          "get": {
            "tags": [
              "view all Mentors"
            ],
            "summary": "Returns all mentors",
            "description": "",
            "operationId": "get all mentors",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token must be provided in this box"
               }
            ],
            "responses": {
              "200": {
                "description": "List of all mentor",
                "schema": {
                  "type": "object",
                  "example": {
                    "id": 4,
                    "first_name": "bavakure",
                    "last_name": "eric",
                    "email": "amani@gmail.com",
                    "password": "kigali",
                    "address": "kigali",
                    "bio": "engineer",
                    "status": "mentor",
                    "occupation": "engineer",
                    "expertise": "engineer"
                  }
                }
              },
              "401":{
                "description": "Token not provided"
              },
              "404":{
                "description": "no mentor found"
              }
            }
          }
        },
        "/mentors<:id>": {
          "get": {
            "tags": [
              "Specific mentor"
            ],
            "summary": "Returns one mentor",
            "description": " ",
            "operationId": "getmentor",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "description": "ID of the mentor",
                "required": true,
                "type": "integer",
                "format": "int64"
              },
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token must be provided in this box"
               }
            ],
            "responses": {
              "200": {
                "description": "specific mentor",
                "schema": {
                  "type": "object",
                  "example": {
                    "id": 5,
                    "first_namr": "amani",
                    "last_name": "murera",
                    "email": "amanie@gmail.com",
                    "password": "kigali",
                    "address": "kigali",
                    "bio": "Doctor",
                    "status": "mentor",
                    "occupation": "Doctor",
                    "expertise": "Doctor"
                  }
                }
              },
              
              "401":{
                "description": "Token not provided"
              },
              "404":{
                "description": "Such mentor is not found"
              }
            
              
            }
          }
        },
        "/sessions": {
          "post": {
            "tags": [
              "Create Mentorship session"
            ],
            "summary": "Create mentorship session",
            "description": "",
            "operationId": "create sessions",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token must be provide in this box "
               },
              {
                "in": "body",
                "name": "body",
                "description": "Created session object",
                "required": true,
                "schema": {
                  "$ref": "#/definitions/sessions"
                }
              }
            ],
            "responses": {
              "201": {
                "description": "sessions created successfully",
                "schema":{
                  "type":"object",
                  "example": {
                    "status": 200,
                    "data": {
                        "Sessionid": 1,
                        "mentorId": 4,
                        "menteeId": 5,
                        "questions": "ffffffffffffffff",
                        "status": "pending"
                    }
                  }
                }
              },
              "404":{
                "description": "Such mentor is not found"
              },
              "401":{
                "description": "token not providen"
              }
              
            }
          }
        },
        "/sessions/<:id>/accept": {
          "patch": {
            "tags": [
              "Accept Mentorship session"
            ],
            "summary": "reject mentorship request",
            "description": "",
            "operationId": "acceptRequest",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token must be providen in this box "
               },
              {
                "in": "path",
                "name": "id",
                "description": "acccept mentorship request",
                "required": true
              }
            ],
            "responses": {
              "201": {
                "description": "accepted mentorship successfully",
                "schema":{
                  "example":{
                    "status": 200,
                    "data": {
                        "Sessionid": 2,
                        "mentorId": 3,
                        "menteeId": 1,
                        "questions": "ffffffffffffffff",
                        "menteeEmail": "amanidiope@gmail.com",
                        "status": "accepted"
                    }
                  }
                }
              },
              "404":{
                "description": "Session not found"
              },
              
              "401":{
                "description": "you are not a mentor"
              },
              "400":{
                "description": "bad request"
              }
               
              
            }
          }
        },
        "/sessions/<:id>/reject": {
          "patch": {
            "tags": [
              "Reject Mentorship session"
            ],
            "summary": "reject mentorship request",
            "description": "",
            "operationId": "rejectRequest",
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                "name": "authorization",
                "in": "header",
                "required": true,
                "type": "string",
                "description": "The token to provide in this box must start with adminToken then space"
               },
              {
                "in": "path",
                "name": "id",
                "description": "acccept mentorship request",
                "required": true
              }
            ],
            "responses": {
              "201": {
                "description": "rejected mentorship successfully",
                "schema":{
                  "example":{
                    "status": 200,
                    "data": {
                        "Sessionid": 2,
                        "mentorId": 3,
                        "menteeId": 1,
                        "questions": "ffff",
                        "menteeEmail": "amanidiope@gmail.com",
                        "status": "reject"
                    }
                  }
                }
              },
              "404":{
                "description": "Session not found"
              },
              
              "401":{
                "description": "you are not a mentor"
              },
              "400":{
                "description": "bad request"
              }
            }
          }
        }
    },
    "definitions": {
      "User": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "bio": {
            "type": "string"
          },
          "occupation": {
            "type": "string"
          },
          "expertise": {
            "type": "string"
          }
        }
      },
      "login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "sessions": {
        "type": "object",
        "properties": {
          "mentorId": {
            "type": "integer"
          },
          "questions": {
            "type": "string"
          }
        }
      }
    },
    "externalDocs": {
      "description": "FreeMentor",
      "url": "https://murera.github.io/FreeMentor/UI/index.html "
    }
  }